version: '2'
services:
    jeta123-app:
        image: jeta123
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jeta123-postgresql:5432/jeta123
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jeta123-postgresql:
        extends:
            file: postgresql.yml
            service: jeta123-postgresql
